### ISSUE TITLE
Allow multiple RPC's to be defined

### ISSUE THREAD

**Issue by danbryan** [cosmos/relayer#1198]
I'd love to see something like this....

```
  osmosis:
    type: cosmos
    value:
      key: default
      chain-id: osmosis-1
      rpc-addr: [
        https://rpc.osmosis.strange.love:443,
        https://rpc.osmosis.strange.love:443
     ]
```

Maybe start simple like, is the first item in the list until it gets `5` non `HTTP 200` codes returned, then it tries the next item in the list.

End goal could be, doing health checks against [chain-registry](https://github.com/cosmos/chain-registry) to determine live peers.

Tasks 
- [x] Create fallback-rpc-addrs command to allow multiple comma separated urls
- [x] Add subcommand to allow adding urls from a file that contains said comma separated url. 
- [ ] Add failsafe to continue to next available url after 5 retires . 
```[tasklist]
### Tasks
```

**Comment by vimystic** [comment]
moving to next print to prioritize updates to taxtooling cron

**Comment by joelsmith-2019** [comment]
I currently have a possible solution in place which involves another go routine which does the following:
- Ping current RPC to ensure liveliness,
- Rotate RPC if offline

I might be creating another wrapper for the RPC Client which handles RPC rotations immediately upon a query failure. This would be more responsive, but requires a little more work.
