### ISSUE TITLE
Additional prometheus metrics

### ISSUE THREAD

**Issue by agouin** [cosmos/relayer#1209]
Add prometheus metrics for error scenarios so that actionable alerts can be created.

```[tasklist]
### Tasks
- [ ] https://github.com/cosmos/relayer/issues/1210
- [ ] https://github.com/cosmos/relayer/issues/1211
- [ ] https://github.com/cosmos/relayer/issues/1212
- [ ] https://github.com/cosmos/relayer/issues/1213
- [ ] https://github.com/cosmos/relayer/pull/1246
```
