### ISSUE TITLE
Meta Issue: IBC 1.0 Readiness

### ISSUE THREAD

**Issue by jackzampolin** [cosmos/relayer#281]
- [x] `config` - CRUD for all resources
- [x] `chains` - CRUD for all resources
- [x] `paths` - CRUD for all resources
- [x] `keys` - CRUD for all resources
- [x] `light` - CRUD for all resources
- [x] `tx`
    - [x] `link`
    - [x] `relay` - this command may need some rethink wrt acks, not fully working
    - [x] `transfer`
    - [x] `clients` - working client creation and update
    - [x] `update-clients` - added this command and it is working
    - [x] `connection`
    - [x] `channel`
    - [x] `channel-close`
    - [x] `raw`
- [x] `q`
    - [x] `unrelayed` - this command may need some rethink wrt ack, not fully working
    - [x] `account`
    - [x] `balance` - need to ensure that output here has IBC denoms disambiguated
    - [x] `header`
    - [x] `node-state` - blocked on https://github.com/cosmos/cosmos-sdk/pull/7302
    - [x] `txs`
    - [x] `tx`
    - [x] `client`
    - [x] `clients` - https://github.com/cosmos/cosmos-sdk/issues/7303
    - [x] `connection` - ideally the `version` field here could be a bit more human readable.
    - [x] `connections` - https://github.com/cosmos/cosmos-sdk/issues/7304
    - [x] `client-connections` - blocked on https://github.com/cosmos/cosmos-sdk/pull/7302
    - [x] `channel` 
    - [x] `channels` - https://github.com/cosmos/cosmos-sdk/issues/7306
    - [x] `connection-channels` - https://github.com/cosmos/cosmos-sdk/issues/7304
    - [x] `packet-commit`
    - [ ] `packet-ack` - UNIMPLEMENTED
- [x] `start` - currently broken will fix
- [x] `dev` - need to decide if we keep these
  - [x] `gaia`
  - [x] `faucet`
  - [x] `relayer`
  - [x] `listen`
  - [x] `genesis`
- [x] `testnets` - need to audit and decide if we keep these
  - [x] `faucet`
  - [x] `request`
- [x] `version`

**Comment by jackzampolin** [comment]
Closing this issue and moving to specific issues and the `1.0` tag for tracking work.
